on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub dispatch event
        run: |
          curl --request POST 'https://api.github.com/repos/blendthink/linkmark-android/dispatches' \
          --header 'Authorization: Bearer ${{secrets.API_KEY_FOR_GITHUB_ACTIONS}}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "event_type": "linkmark-api-updated"
          }'
