on:
  push:
    branches: master
    paths: linkmark.yaml

jobs:
  update:
    name: update_android_api_client
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v2
        with:
          ref: master
          path: api
      - name: Check out android repository
        uses: actions/checkout@v2
        with:
          repository: blendthink/linkmark-android
          ref: master
          path: android
          token: ${{ secrets.API_KEY_FOR_GITHUB_ACTIONS }}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate API client
        run: |
          cp ./api/linkmark.yaml ./android/linkmark.yaml
          cd ./android
          rm -rf ./apiclient/build/openApiGenerator/linkmark
          rm -rf ./apiclient/src/main/kotlin/dev/honwakalab/linkmark/apiclient/infrastructure
          rm -rf ./apiclient/src/main/kotlin/dev/honwakalab/linkmark/apiclient/linkmark
          sh ./update_api_client.sh
          cp -r ./apiclient/build/openApiGenerator/linkmark/src/main/kotlin/dev/honwakalab/linkmark/apiclient/infrastructure ./apiclient/src/main/kotlin/dev/honwakalab/linkmark/apiclient/infrastructure
          cp -r ./apiclient/build/openApiGenerator/linkmark/src/main/kotlin/dev/honwakalab/linkmark/apiclient/linkmark ./apiclient/src/main/kotlin/dev/honwakalab/linkmark/apiclient/linkmark
          cd ./..
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          path: android
          token: ${{ secrets.API_KEY_FOR_GITHUB_ACTIONS }}
          commit-message: Update API client
          title: Update API client (auto generated)
          body: This PR was automatically generated by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          branch: feature/update_api_client
          branch-suffix: timestamp
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: '#35F09C'
          SLACK_ICON: https://github.com/blendthink.png?size=48
          SLACK_USERNAME: BOT
          SLACK_TITLE: Create Pull Request
          SLACK_MESSAGE: 'Pull Request URL: ${{ steps.cpr.outputs.pull-request-url }}'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
