on:
  push:
    branches: master
    paths: linkmark.yaml

jobs:
  update:
    name: update_android_api_client
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v2
        with:
          ref: master
          path: api
      - name: Check out android repository
        uses: actions/checkout@v2
        with:
          repository: blendthink/linkmark-android
          ref: master
          path: android
          token: ${{ secrets.secrets.API_KEY_FOR_GITHUB_ACTIONS }}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate API client
        run: |
          cp ./api/linkmark.yaml ./android/linkmark.yaml
          cd ./android
          sh ./update_api_client.sh
          cd ./..
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          path: android
          token: ${{ secrets.API_KEY_FOR_GITHUB_ACTIONS }}
          commit-message: Update API client
          title: Update API client (auto generated)
          body: This PR was automatically generated by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          branch: feature/update_api_client
          branch-suffix: timestamp
